steps:
  # npm install
  - name: 'gcr.io/cloud-builders/npm'
    args: ['install']
    dir: 'atd-graphql-server'
  # run tests
  - name: 'gcr.io/cloud-builders/npm'
    args: ['run', 'test']
    dir: 'atd-graphql-server'
  # Build Container
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/atd-graphql-server:$REVISION_ID', '.']
    dir: 'atd-graphql-server'
  # Push Container
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/atd-graphql-server:$REVISION_ID']
    dir: 'atd-graphql-server'
  # Deploy Container
  - name: 'gcr.io/cloud-builders/kubectl'
    args:
      - 'set'
      - 'image'
      - 'deployment/atd-graphql-server'
      - 'atd-graphql-server=gcr.io/$PROJECT_ID/atd-graphql-server:$REVISION_ID'
    env:
      - 'CLOUDSDK_COMPUTE_ZONE=us-east4-a'
      - 'CLOUDSDK_CONTAINER_CLUSTER=atd-project-cluster'
    dir: 'atd-graphql-server'
